### PR TITLE
Drop EOL'ed PHP versions

### PR DESCRIPTION
**Pull request by deviantintegral**
This should fix builds failing on master as they're pulling in xdebug 3 which has new configuration options.

The minimum supported PHP version is now PHP 7.3, based on 7.2 being EOL at https://www.php.net/supported-versions

### CODE REVIEW

**Comment by deviantintegral** [comment]
I was going to do PHP 8, but it looks like there's some issues with the symfony serializer picking up the right properties when deserializing. As well, there's ~16 PHPUnit deprecations, along with the complete removal of `assertArraySubset`: https://github.com/sebastianbergmann/phpunit/issues/3494

**Review by m4olivei — APPROVED** [review]
This looks great! Thanks for doing this @deviantintegral .

**Comment by m4olivei** [comment]
Hum, the PHP 7.4 job failed on master after I merged it :cry: :thinking: . Any ideas @deviantintegral ?

**Comment by deviantintegral** [comment]
@m4olivei i wonder if circle was having issues, or if there was a buggy xdebug update? `pecl install xdebug` shouldn't segfault :D

https://app.circleci.com/pipelines/github/Lullabot/mpx-php/53/workflows/2d9b43b9-ea28-4376-b634-aa29ea38f687/jobs/2597

```
Build process completed successfully
Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so'
/bin/bash: line 1:   791 Segmentation fault      (core dumped) pecl install xdebug
```

**Comment by m4olivei** [comment]
@deviantintegral I thought the same. I tried it again this morning and it still fails. One thing I noticed is there is a mismatch in the xdebug extensions referenced in the CircleCI `config.yml`. Is that intentional?

https://github.com/Lullabot/mpx-php/blob/master/.circleci/config.yml#L81-L88

eg. on line 81 it's `no-debug-non-zts-20200930` and on lines 82 and 88 it's `no-debug-non-zts-20190902`.

**Comment by m4olivei** [comment]
I got a bit further with that :):

https://github.com/Lullabot/mpx-php/pull/168
https://circleci.com/gh/Lullabot/mpx-php/2609?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request merged**
